### ISSUE TITLE
MagiskOnWSALocal release

### ISSUE THREAD

**Issue by wuyilingwei** [HidemaruOwO/HidemaruOwO#1]
https://github.com/LSPosed/MagiskOnWSALocal/issues/682

I have a solution, use github action to simulate user operations.

you can see me project https://github.com/yige-yigeren/MagiskOnWSAOnlineBuild

**Comment by wuyilingwei** [comment]
This is the best solution I could find, small deployments for self-use will not trigger abuse warnings.
At the same time, it will not affect the main project: you can’t ban the project because there are many clone operations.

**Comment by HidemaruOwO** [comment]
I forgot to close the project.

**Comment by HidemaruOwO** [comment]
Oh. just rescind the release.
